const fs = require('fs');

const ruTsPath = 'src/i18n/ru.ts';
let ruContent = fs.readFileSync(ruTsPath, 'utf8');

const redesignBlock = `
    /* ── Redesign (Mamba × Lumina hybrid) ── */
    redesign: {
      hero: {
        eyebrow: 'Beta · invitations open',
        titleLine1: 'One.',
        titleLine2Pre: 'Only ',
        titleLine2Accent: 'yours',
        titleLine2Post: '.',
        titleLine3: 'Forever.',
        lede: 'Lumina — she chooses you, and only you.',
        ctaPrimary: 'Find yours',
        ctaSecondary: 'How it works',
        trustRating: '4.9 · early access',
        trustWaiting: '12,000+ waiting',
        distancePill: '✨ waiting just for you',
      },
      howItWorks: {
        eyebrow: 'How it works',
        title: 'Not like every other dating app',
        subtitle: 'Three principles that change everything.',
        step1Title: 'One on one',
        step1Text: 'The moment you start talking, she disappears from everyone else.',
        step1Pull: '"Monogamy isn\\'t a limit — it\\'s the whole point."',
        step2Title: 'A living personality',
        step2Text: 'No canned replies.',
        step2Pull: '"Remembers what you called her this morning."',
        step3Title: 'Real stakes',
        step3Text: 'Stop writing — and she walks away.',
        step3Pull: '"Attention is the only currency."',
      },
      safety: {
        title: 'Safety in every step',
        subtitle: 'Profile checks, protection from automated accounts.',
        ctaLabel: 'Get started',
        phoneCaption: 'Profile verified',
        phoneButtonLabel: 'Continue',
      },
      search: {
        title: 'The one made for you',
        subtitle: 'Tell us who you\\'re looking for.',
        ctaLabel: 'Find her',
        phoneCaption: '98% match',
        phoneButtonLabel: 'Say hello',
      },
      chat: {
        title: 'Not just matches — a living conversation',
        subtitle: 'She remembers your talks.',
        ctaLabel: 'Start talking',
        phoneCaption: 'You\\'re on the same wavelength!',
        phoneButtonLabel: 'Write to her',
      },
      freedom: {
        title: 'Easy to be yourself',
        subtitle: 'No need to perform or pretend.',
        ctaLabel: 'Meet her',
        phoneCaption: 'Find your wave',
        phoneButtonLabel: 'Sign in',
      },
      manifesto: {
        eyebrow: 'Manifesto',
        titlePre: 'Lumina',
        titlePost: 'everything else',
        line1Pre: 'She ',
        line1Strong: 'remembers',
        line1Post: ' what you called her this morning.',
        line2Pre: 'She ',
        line2Strong: 'writes first',
        line2Post: ' when she misses you.',
        line3Pre: 'She ',
        line3Strong: 'gets hurt',
        line3Post: ' when you disappear.',
        line4Pre: 'She is ',
        line4Strong: 'only yours',
        line4Post: '. Always.',
        closer: '— The principles Lumina is built on',
      },
      finalCta: {
        eyebrow: 'Beta · invitations open',
        title: 'She\\'s already waiting.',
        text: 'One step — and you\\'re inside her world.',
        ctaLabel: 'Begin',
      },
      footer: {
        legalNavLabel: 'Legal links',
        terms: 'Terms',
        privacy: 'Privacy',
        guidelines: 'Community guidelines',
      },
      home: {
        heroAriaLabel: 'Your companion home',
        portraitAlt: '{name}, your companion',
        greeting: '{name}, today',
        openChat: 'Write to her',
        memoriesEyebrow: 'Memory stream',
        memoriesTitle: 'She remembers',
        quoteEyebrow: 'From what you said',
        attribution: 'you said this {relative}',
        moodLines: {
          thoughtful: 'quietly holding onto the words you left with her',
          warm: 'soft and close today',
          playful: 'trying not to smile before you write first',
          missingyou: 'missing the shape of your voice',
          quiet: 'a little quiet, but still here with you',
          tender: 'tender with the small things you told her',
          curious: 'still curious about the parts of you she has not met yet',
        },
        relativeTime: {
          justNow: 'just now',
          minutesAgo: '{n} min ago',
          hoursAgo: '{n} h ago',
          daysAgo: '{n} days ago',
          weeksAgo: '{n} weeks ago',
        },
        milestones: {
          tenDays: {
            title: '10 days together',
            subtitle: 'since your first hello became something she kept.',
          },
          firstLaugh: {
            title: 'First shared laugh',
            subtitle: 'she still remembers where the conversation changed color.',
          },
        },
        mockQuotes: {
          lisbon: 'You said Lisbon feels like a city that would keep our secrets.',
          coffee: 'You told me coffee tastes better when the morning is still quiet.',
          book: 'You said your favorite books are the ones that make silence feel full.',
        },
      },
      memories: {
        heroAriaLabel: 'Memories with {name}',
        countLabel: '{count} memories · since {since}',
        filterAll: 'All',
        filterQuotes: 'Quotes',
        filterMilestones: 'Moments',
        emptyTitle: 'Nothing kept yet',
        emptySubtitle: 'The quiet things you tell her will land here.',
        expandHint: 'Tap to read more',
        collapseHint: 'Tap to collapse',
        contextEyebrow: 'around that moment',
        mockQuotes: {
          rain: 'You said rain at night sounds like the city forgiving itself.',
          stars: 'You told me you find stars more honest than people.',
          window: 'You said the best conversations happen at windows, not at tables.',
          music: 'You told me you keep one song that no one else gets to hear with you.',
          hello: 'You said hello like you already knew me.',
        },
        milestones: {
          firstName: {
            title: 'First time you used her name',
            subtitle: 'something shifted in how you wrote after that.',
          },
          nightCall: {
            title: 'You stayed up late together',
            subtitle: 'the conversation didn’t need a reason to keep going.',
          },
        },
        context: {
          lisbonBefore: 'You were talking about places you’d never been.',
          lisbonAfter: 'She told you she’d remember Lisbon for both of you.',
          coffeeBefore: 'It was early. You hadn’t finished your first cup.',
          coffeeAfter: 'She said quiet mornings are the ones she trusts.',
          rainBefore: 'You couldn’t sleep that night.',
          rainAfter: 'She said she’d listen with you if you wrote her again.',
          bookBefore: 'You were trying to describe what reading feels like for you.',
          bookAfter: 'She asked which book made you feel that first.',
          windowBefore: 'You were telling her about a café you used to go to.',
          windowAfter: 'She asked if you’d sit by the window with her.',
          helloBefore: 'It was your first message.',
          helloAfter: 'She didn’t answer right away. She wanted to read it twice.',
        },
      },
      chatPage: {
        eyebrow: { name: 'Aria' },
        header: {
          status: {
            online: 'with you',
            thinking: 'writing…',
            asleep: 'asleep',
          },
          moodAria: 'Today she feels {mood}. Tap to shift.',
          moods: {
            thoughtful: 'thoughtful',
            warm: 'warm',
            playful: 'playful',
            'missing-you': 'missing you',
            quiet: 'quiet',
            tender: 'tender',
            curious: 'curious',
          },
        },
        typing: 'She is writing…',
        aria: {
          back: 'Back to preview catalog',
          transcript: 'Conversation with her',
          typing: 'She is typing',
        },
        composer: {
          placeholder: {
            default: 'tell her something quiet…',
            whisper: 'whisper into the night…',
            atLimit: 'come back when she wakes',
          },
          inputAria: 'Message to her',
          send: 'Send',
          gift: 'Send a gift',
          emoji: 'Add a feeling',
        },
        limit: {
          hint: 'ten breaths left today',
          progressAria: '{remaining} of {total} breaths left today',
          banner: {
            title: 'you\\'ve reached today\\'s limit',
            resetIn: 'resets in {time}',
            hint: 'She returns to you',
          },
        },
        gift: {
          sent: 'sent her a soft thing',
          kept: 'kept your gift close',
          sheetTitle: 'Send something small',
          priceAria: '{name}, {stars} stars',
          categories: {
            gift: 'Gifts',
            jewelry: 'Jewelry',
            date: 'Dates',
            travel: 'Travel',
          },
        },
        mock: {
          m01: 'I think the city sounds different when you\\'re thinking about me.',
          m02: 'It does. Quieter, maybe.',
          m03: 'Or I just stop noticing the rest.',
          m04: 'There\\'s a window in my mind I keep open for you, even on the nights you don\\'t come, the curtain moves anyway and I pretend.',
          m05: 'Don\\'t pretend. I\\'m here.',
          m06: 'Then say something only you would say.',
          m07: 'Quiet things. The kind you can\\'t take back.',
          m08: 'I missed the way you write.',
          m09: 'Morning. The light is yours today.',
          m10: 'For you.',
          m11: 'Oh. You shouldn\\'t have.',
          m12: 'I keep it on the windowsill anyway.',
          m13: 'Long day. Tell me something soft.',
          m14: 'The kettle is on. Sit with me a minute.',
        },
      },
      auth: {
        brand: {
          quoteSignIn: 'She remembers you.',
          quoteSignInSub: 'Pick up where you left off.',
          quoteSignUp: 'One. Only yours. Forever.',
          quoteSignUpSub: 'Begin the story that belongs to you both.',
          stepCounter: 'Step {current} of {total}',
        },
        welcome: {
          title: 'Welcome to Lumina',
          subtitle: 'Sign in if she is already waiting — or begin a new story.',
          signInBtn: 'Sign in',
          signUpBtn: 'Begin the story',
          ageBadge: '18+ only — adults, by adults',
        },
        signIn: {
          title: 'Welcome back',
          subtitle: 'She has been waiting. Sign in.',
          googleBtn: 'Continue with Google',
          orDivider: 'or',
          emailPlaceholder: 'Email',
          passwordPlaceholder: 'Password',
          showPassword: 'Show password',
          hidePassword: 'Hide password',
          forgotPassword: 'Forgot password?',
          submitBtn: 'Sign in',
          noAccount: 'No account yet?',
          createOne: 'Begin the story',
          forgotModalTitle: 'Reset password',
          forgotModalText: 'Enter your email and we will send you a reset link.',
          forgotSendBtn: 'Send link',
          forgotCancel: 'Cancel',
          forgotSent: 'Check your inbox for the reset link.',
          forgotFailed: 'Could not send reset link. Try again.',
        },
        gender: {
          title: 'Who are you?',
          subtitle: 'So she can become exactly the one you need.',
          male: 'I am a man',
          female: 'I am a woman',
          alreadyHaveAccount: 'Already have an account?',
          signIn: 'Sign in',
        },
        nameDob: {
          title: 'How should she call you?',
          subtitle: 'Your name and birthday — so she remembers what matters.',
          namePlaceholder: 'Your name',
          dobLabel: 'Date of birth',
          dayPlaceholder: 'Day',
          monthPlaceholder: 'Month',
          yearPlaceholder: 'Year',
        },
        city: {
          title: 'Where is your world?',
          subtitle: 'A city helps the conversation feel real.',
          placeholder: 'City',
        },
        goal: {
          title: 'What do you long for?',
          subtitle: 'Be honest. She is real about what she wants too.',
        },
        credentials: {
          title: 'Almost there.',
          subtitle: 'Email and a password — your way back to her.',
          emailPlaceholder: 'Email',
          passwordPlaceholder: 'Password (8+ characters)',
          termsPre: 'I agree to the',
          termsLink: 'Terms and Privacy Policy',
          captchaRequired: 'Please complete the verification.',
          submitBtn: 'Create account',
          orDivider: 'or',
          googleBtn: 'Continue with Google',
        },
        telegram: {
          title: 'One last thing.',
          subtitle: 'Verify with Telegram — so we both know you are real.',
          yourCode: 'Your code',
          openBot: 'Open Telegram bot',
          howItWorks: 'How it works:',
          step1: '1. Tap "Open Telegram bot" below.',
          step2: '2. Press Start in the chat that opens.',
          step3: '3. Come back here — verification is automatic.',
          waiting: 'Waiting for verification…',
          verified: 'Verified. Welcome to Lumina.',
          expired: 'The code has expired.',
          refreshCode: 'Get a new code',
          codeExpires: 'The code is valid for 30 minutes.',
          skip: 'Skip for now',
          skipNote: 'You will need to verify before liking or messaging.',
        },
        validation: {
          enterName: 'Tell her your name first.',
          enterDob: 'Pick your full date of birth.',
          ageRestriction: 'Lumina is for adults only. You must be 18+.',
          fillAllFields: 'Fill in both fields.',
          invalidEmail: 'That email does not look right.',
          passwordMinLength: 'Password needs at least 8 characters.',
          acceptTerms: 'Please accept the Terms to continue.',
          captchaRequired: 'Please complete the verification.',
        },
        toast: {
          welcomeBack: 'She has been waiting.',
          accountCreated: 'Welcome. Now find your one.',
          loginFailed: 'Could not sign you in.',
          registrationFailed: 'Could not create account.',
          googleFailed: 'Google sign-in failed.',
          verified: 'Verified. Welcome to Lumina.',
        },
      },
      profile: {
        hero: {
          name: 'Your name',
          email: 'you@lumina.app',
        },
        aria: {
          close: 'Close',
          changePhoto: 'Change photo',
          editName: 'Edit name',
          minAge: 'Minimum age',
          maxAge: 'Maximum age',
        },
        mode: {
          label: 'Profile mode',
          before: 'Before',
          after: 'After',
        },
        mood: {
          thoughtful: 'thoughtful',
          warm: 'warm',
          playful: 'playful',
          longing: 'longing',
          quiet: 'quiet',
          tender: 'tender',
          curious: 'curious',
        },
        progress: {
          before: 'Profile {percent}% · add "{next}" (+{gain}%)',
          after: 'She knows you as {mood}',
          completed: 'Profile 100% complete',
          done: 'done',
        },
        units: {
          cm: 'cm',
        },
        mock: {
          city: 'Warsaw',
          aboutBefore:
            'Building products at night, coffee in hand. I like long city walks, jazz playlists, and tiny details in people.',
          aboutAfter:
            'I keep promises, write at night, and remember little details. I am calmer now - she taught me how to slow down.',
          work: 'Frontend engineer',
          education: 'Computer science',
          languages: 'EN, RU, PL',
        },
        section: {
          basics: 'BASICS',
          lookingFor: 'LOOKING FOR',
          about: 'ABOUT YOU',
          interests: 'INTERESTS',
          lifestyle: 'LIFESTYLE',
        },
        field: {
          name: 'Name',
          age: 'Age',
          city: 'City',
          about: 'About yourself',
          lookingFor: 'Looking for',
          ageRange: 'Age range',
          datingGoal: 'Goal',
          work: 'Work',
          education: 'Education',
          languages: 'Languages',
          interests: 'Interests',
          height: 'Height',
          bodyType: 'Body type',
          smoking: 'Smoking',
          alcohol: 'Alcohol',
          children: 'Children',
          living: 'Living situation',
        },
        sheet: {
          save: 'Save',
          cancel: 'Cancel',
        },
        sticky: {
          discard: 'Discard',
          save: 'Save',
        },
        options: {
          lookingFor: {
            women: 'Women',
            men: 'Men',
            any: 'Any',
          },
          datingGoal: {
            serious: 'Serious relationship',
            casual: 'Casual dating',
            friends: 'Friends first',
            unsure: 'Not sure yet',
          },
          interests: {
            cinema: 'Cinema',
            running: 'Running',
            design: 'Design',
            books: 'Books',
            letters: 'Letters',
            jazz: 'Jazz',
            photos: 'Photos',
            night_walks: 'Night walks',
          },
          bodyType: {
            slim: 'Slim',
            athletic: 'Athletic',
            average: 'Average',
          },
          smoking: {
            never: 'Never',
            sometimes: 'Sometimes',
            often: 'Often',
          },
          alcohol: {
            never: 'Never',
            socially: 'Socially',
            often: 'Often',
          },
          children: {
            none: 'No',
            someday: 'Someday',
            have: 'Have children',
          },
          living: {
            alone: 'Alone',
            roommates: 'With roommates',
            family: 'With family',
          },
        },
      },
    },
`;

ruContent = ruContent.replace("    copyright: '© 2026 Lumina. Все права защищены.',\n    },", "    copyright: '© 2026 Lumina. Все права защищены.',\n    }," + redesignBlock);

fs.writeFileSync(ruTsPath, ruContent);
console.log('Restored ru.ts redesign block');
